/* Copyright (c) 2022 Reminano */

module.exports = {
  TASK_COMMENTS_ERRORS: {
    INSERT_FAILED: 'INSERT_FAILED',
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
    UPDATE_FAILED: 'UPDATE_FAILED',
    DELETE_FAILED: 'DELETE_FAILED',
  },
};
