/* Copyright (c) 2022-2023 TORITECH LIMITED 2022 */

module.exports = {
  BANNER_SECTION: {
    STATIONS: 10,
  },
  BANNER_ERROR: {
    NOT_FOUND: 'NOT_FOUND',
    INVALID_BANNER_ID: 'INVALID_BANNER_ID',
    UPDATE_FAILED: 'UPDATE_FAILED',
    DELETE_FAILED: 'DELETE_FAILED',
  },
};
