/* Copyright (c) 2023 TORITECH LIMITED 2022 */

module.exports = {
  STATION_REPORT_DISPLAY_DATE_FORMAT: 'YYYY/MM/DD',
  REPORT_DATE_DISPLAY_FORMAT: 'DD/MM/YYYY',
  REPORT_DATE_DATA_FORMAT: 'YYYYMMDD',
};
