/* Copyright (c) 2022-2023 Reminano */

/**
 * Created by A on 7/18/17.
 */
'use strict';

module.exports = {
  BONUS_TRX_STATUS: {
    NEW: 'New',
    WAITING: 'Waiting',
    PENDING: 'Pending',
    COMPLETED: 'Completed',
    DELETED: 'Deleted',
    CANCELED: 'Canceled',
  },
  BONUS_TRX_CATEGORY: {
    WITHDRAW_TO_EXTERNAL: 10,
    WITHDRAW_TO_WALLET: 20,
  },
  BONUS_TRX_ERROR: {
    INVALID_TRANSACTION: 'INVALID_TRANSACTION',
    TRANSACTION_ALREADY_PROCESSED: 'TRANSACTION_ALREADY_PROCESSED',
    TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  },
  BONUS_PAYMENT_DATE_DISPLAY_FORMAT: 'DD/MM/YYYY',
  BONUS_PAYMENT_DATE_DB_FORMAT: 'YYYYMMDD',
};
