/* Copyright (c) 2022-2023 TORITECH LIMITED 2022 */

module.exports = {
  CHECKING_STATUS: {
    NEW: 'New',
    SENDING: 'Processing',
    COMPLETED: 'Completed',
    FAILED: 'Failed',
    CANCELED: 'Canceled',
  },
  CUSTOMER_RECORD_PLATE_COLOR: {
    WHITE: 'white',
    BLUE: 'blue',
    YELLOW: 'yellow',
    RED: 'red',
  },
  CUSTOMER_RECORD_ERROR: {
    DUPLICATED_RECORD_IN_ONE_DAY: 'DUPLICATED_RECORD_IN_ONE_DAY',
    INVALID_CUSTOMER_SCHEDULE: 'INVALID_CUSTOMER_SCHEDULE',
    DUPLICATE_LINKED_BOOKING_SCHEDULE: 'DUPLICATE_LINKED_BOOKING_SCHEDULE',
    INVALID_PLATE_NUMBER: 'INVALID_PLATE_NUMBER',
  },
  DATE_DISPLAY_FORMAT: 'DD/MM/YYYY',
  DATE_DB_FORMAT: 'DD/MM/YYYY',
  DATE_DB_SORT_FORMAT: 'YYYYMMDD',
  CHECKING_TIME_07_09: '7h-9h',
  CHECKING_TIME_0930_1130: '9h30-11h30',
  CHECKING_TIME_1330_1500: '13h30-15h',
  CHECKING_TIME_1530_1730: '15h30-17h30',
  WORK_TIME_0730_1630: '7h30-16h30',
  WORK_TIME_0730_1130: '7h30-11h30',
};
