/* Copyright (c) 2022-2024 Reminano */

module.exports = {
  STAFF_ERROR: {
    DUPLICATED_USER: 'DUPLICATED_USER',
    DUPLICATED_USER_EMAIL: 'DUPLICATED_USER_EMAIL',
    DUPLICATED_USER_PHONE: 'DUPLICATED_USER_PHONE',
    DUPLICATE_REFERCODE: 'DUPLICATE_REFERCODE',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    USER_LOCKED: 'USER_LOCKED',
    NOT_FOUND: 'STAFF_NOT_FOUND',
    UPDATE_FAILED: 'STAFF_UPDATE_FAILED',
    USERNAME_OR_PASSWORD_NOT_MATCH: 'USERNAME_OR_PASSWORD_NOT_MATCH',
  },
  STAFF_ACTIVE: '1',
};
