/* Copyright (c) 2023 TORITECH LIMITED 2022 */

module.exports = {
  PAYMENT_ERROR: {
    WRONG_MOMO_CONFIG_DATA: 'WRONG_MOMO_CONFIG_DATA',
    RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
    WRONG_PAYMENT_METHOD: 'WRONG_PAYMENT_METHOD',
    INVALID_ORDER: 'INVALID_ORDER',
    ALREADY_PAID: 'ALREADY_PAID', //đã thanh toán
  },
};
