/* Copyright (c) 2023 TORITECH LIMITED 2022 */

module.exports = {
  STATISTICAL_ERROR: {
    WRONG_FILTER_DATE: 'WRONG_FILTER_DATE',
  },
  DEFAULT_LIMIT_DEVICES: 2,
  DEFAULT_STAFF_PER_DEVICES: 3,
  DEFAULT_MAX_VEHICLE_PER_DEVICES_PER_DAY: 40,
};
